### ISSUE TITLE
Add 'Share' button to saved resources

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#177]
On Saved Resources
* Remove the Upload & Download arrows
* Add button 'Share' which will create a link that looks like `https://communityconnect.netlify.com/map/?resources=19,3`
* share button will show user a the link via text box & with simple instructions or some icon

this is the copy to clipboard icon github uses:
![image](https://user-images.githubusercontent.com/757518/52314619-87f4d400-2981-11e9-87ea-24c54b901de1.png)

**Comment by sayansaha1143** [comment]
@galiat @ndesai06 So since now we decided that this share button will open a new tab which leads us to the map with all the saved resources, with the exact URL that is needed to be shared. 

My question is now do we need the "To Map" button which currently is present below the saved resources panel? Since basically, both would be doing pretty much the same thing. 

Or do let me know if I missed something.

**Comment by galiat** [comment]
That is a good point. Def worth talking about. Going to defer to to Nevil & UX folks on this one.

cc @AsstroGrill @lizbur10 & Will

**Comment by galiat** [comment]
(@sanktion13 is Will)
