### ISSUE TITLE
How can we visually separate Category, Search & Sort from the Card list?

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#209]
On admin view there is no visual separation between search/sort/filter & the org cards. UX folks - any ideas on how to make this better?

https://communityconnect.netlify.com/admin

**Comment by AsstroGrill** [comment]
Sorry, just getting to this now. I'm thinking of some sort of color division, if it isn't too complicated to implement now. I know launch is in, like, 4 days (!!!!!), so I can come up with something else if this doesn't work in the meantime :) 

![ccdivisioncolor](https://user-images.githubusercontent.com/45612032/53370326-7452e280-391b-11e9-8ea4-a36a06140b8e.jpg)

**Comment by AsstroGrill** [comment]
Saved resources would still be next to the title, and the grey bar just represents the first third division, not actually a line there

It might be wise to move the Saved Resources button, though, to the right upper hand corner. I'm not sure how difficult that would be to implement either, but it would make the layout more even. Something to the effect of this: 

![ccdivisioncolorsr](https://user-images.githubusercontent.com/45612032/53370635-3d310100-391c-11e9-86f9-2dc4501cf041.jpg)

It might not seem very important, but I believe it would make the general flow easier to understand for users, especially since the box pops up on the right when you click on Saved Resources

**Comment by timtheguy** [comment]
This issue hasn't seen any activity in a while, and both our screens and designs have shifted focus a bit since then. Closing for the time being - this leaves the proposed designs available for future developers to review, until future notice!
