### ISSUE TITLE
Adding an alert box notification after adding to your "saved resources" cart

### ISSUE THREAD

**Issue by RajChaudhry** [codeforboston/communityconnect#326]
Currently, there is no indication other than the check box to indicate to a SW that they've added a resource to their cart. Having a small alert box that pops up after clicking on the button would fix this.

**Comment by acharliekelly** [comment]
But not the kind of alert box that requires you to click OK, because that gets really annoying, especially if you've used the app before and already know what happens when you add a resource.
Speaking of, demanding that you acknowledge removal of a resource is also pretty annoying. Is it possible to have a non-modal alert message?

**Comment by RajChaudhry** [comment]
Yes, it would preferably not be a modal, just an alert box that pops up near the top of the screen and fades after a few seconds. I can also create another issue and work on replacing the modal alert when removing resources to an alert box that fades away.

**Comment by RajChaudhry** [comment]
Addressed via #353
