### ISSUE TITLE
YELP API - NO Imagery?

### ISSUE THREAD

**Issue by ArgenisDLR** [codeforboston/communityconnect#338]
Personally, I see no images which I think would help with the visual representation of the clinic. I suggest we use a yelp api or any other api that can connect the community center to image file. Memory is a concern!

**Comment by RajChaudhry** [comment]
This is an interesting idea. On one hand, it would be really nice to have images associated with each resource. The problem is that the majority of these health resources are not currently known well in the public, so there isn't many pictures of them available online, at least from what I could find on common directory websites like yelp. I think this would be a good idea to implement in the future though. Maybe even incorporate a Google Maps Streetview of each place?

**Comment by ArgenisDLR** [comment]
Yeah, I was also thinking that there should be a functionality that when you tap the address, it can either take the user to the streetview like you said or just open a separate window that shows the location.

**Comment by RajChaudhry** [comment]
we had it in a previous build, but the functionality stopped at some point. see #316
