### ISSUE TITLE
re-map code to use Nevil's spreadsheet 

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#5]
code currently uses: 
https://docs.google.com/spreadsheets/d/108aVfUjdRr_je1Pzx-axkOZTMMtdug7iyVH1m3BsnRw/edit#gid=0

code should use: 
https://docs.google.com/spreadsheets/d/e/2PACX-1vRVzMlKCR7IvRTTSqCzRq4CG7YiTtrkzNAkzuMfh-RgBtl7FFj650O5rwS1uE0xWwfnaFeyFmY6u1uk/pubhtml

**Comment by sayansaha1143** [comment]
So you can try doing this and see if the URL changes. And we should be able to use that URL.
![image](https://user-images.githubusercontent.com/23369510/45395381-e51f7000-b603-11e8-9e97-a2034c011596.png)

**Comment by irvang** [comment]
Yes, that is exactly what I was referring to. The problem is that the link is already a shared link, I cannot share it, that is something that needs to be done by Nevil, seems to me.

**Comment by ndesai06** [comment]
What do I have to change in the settings of the sheet to make it available? Or should I create a fresh/separate sheet that pulls its information from the original database?

**Comment by sayansaha1143** [comment]
Yeah so I looked it up. @ndesai06 , so since we were trying to use published link it wasn't working, if you could send us the source URL of your spreadsheet editor after you given access to everyone who has the link (which I am assuming is already the case).

![capture](https://user-images.githubusercontent.com/23369510/45446710-96bdb000-b69b-11e8-90d0-727d78638981.PNG)

The one above is the link for the spreadsheet that we are currently using. You should have a similar link for your spreadsheet. That should work.
