### ISSUE TITLE
Calculate (vs hardcode) defaultZoom & defaultCenter

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#82]
(Note: not critical)

Inspired by 
https://github.com/codeforboston/communityconnect/pull/81

it would be best if the map's defaultZoom & defaultCenter were computed based on the data we want to display rather than hard coded

**Comment by tshin7** [comment]
I wanted to try this one, but I wasn't sure how to go about doing it. What data would we use to calculate them?

**Comment by Khoawala** [comment]
I think this issue will be necessary since the markers on the map changes based on the saved resources. If anyone would like to try, I would look up how to make the map zoom to fit all markers that show up on the map. This could be a start:

https://stackoverflow.com/questions/47239508/how-to-use-fitbounds-in-react-google-map-once-you-have-bounds

**Comment by rahulmotan** [comment]
Hey guys, I'm also working on this one, I came across this link that might be the solution. I spent my weekly hack night to find this and understand our app's code. I'll try my best to finish it by next weekend.

link: https://github.com/tomchentw/react-google-maps/issues/305
