### ISSUE TITLE
Deep Linking: use URL param to show an org

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#92]
Each org now as a key called `id`. 

If the URL contains an id (something like `https://communityconnect.netlify.com?id=3`), set the state as though the user has searched by that orgs name & clicked the pin on the map.

It would make sense in the callsheets function to create a hash where the key is the org's `id` and the value is the index of the org in the `orgs` array.  @microcat49 is doing something similar for lat & long, so talk to him or @galiat if you have any questions about this

related to https://github.com/codeforboston/communityconnect/issues/93

**Comment by lukehollis** [comment]
@galiat @Khoawala I can check this out since it seems related to persisting the list of resources in the URL. Since it looks like there's a few errors with the map and search box right now, can I have more direction on what the state should look like when a url like https://communityconnect.netlify.com?id=3 is visited?
